#%RAML 1.0 DataType

type: object
properties:
  users:
    type: UserObject[]
#    type: array
#    items:
#      type: object
#      properties:
#        username:
#          type: string
#          required: false
#        fullname:
#          type: string
#          required: false
#        age:
#          type: integer
#          required: false
#        gender:
#          type: string
#          required: false
#        dateRegistered:
#          type: string
#          required: false